version: "3"

services:
  static:
    image: tioryuuji159/static-server:latest
    restart: unless-stopped
    volumes:
      - ./files/:/home/static

  blog:
    image: tioryuuji159/blog:latest
    restart: unless-stopped

  start:
    image: tioryuuji159/start:latest
    restart: unless-stopped

  shrine:
    image: tioryuuji159/zenithar-shrine:latest
    restart: unless-stopped
    volumes: 
      - ./database.sqlite:/usr/app/database.sqlite
